// This file is generated by Slice Machine. Update with care!

import CallToAction from './CallToAction';
import ImageCard from './ImageCard';
import Product from './Product';

export {
	CallToAction,
	ImageCard,
	Product,
};

export const components = {
	call_to_action: CallToAction,
	image_card: ImageCard,
	product: Product,
};
